import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "category",
      label: "Tutorial",
      items: [
        "tutorial-basics/create-a-document",
        "tutorial-basics/create-a-blog-post",
        "tutorial-basics/create-a-page",
        "tutorial-basics/deploy-your-site",
        "tutorial-extras/manage-docs-versions",
        "tutorial-extras/translate-your-site",
        "tutorial-basics/congratulations",
      ],
    },
  ],
  frontendSidebar: [
    {
      type: "category",
      label: "Front-End",
      items: [
        "frontend/index",
        "frontend/testing/index",
        "frontend/testing/component-testing/index",
        "frontend/testing/cypress-e2e-testing/index",
      ],
    },
  ],
};

export default sidebars;
