import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "category",
      label: "Tutorial",
      items: [
        "tutorial-basics/create-a-document",
        "tutorial-basics/create-a-blog-post",
        "tutorial-basics/create-a-page",
        "tutorial-basics/deploy-your-site",
        "tutorial-extras/manage-docs-versions",
        "tutorial-extras/translate-your-site",
        "tutorial-basics/congratulations",
      ],
    },
  ],
  frontendSidebar: [
    {
      type: "category",
      label: "Front-End",
      items: [
        "frontend/index",
        {
          type: "category",
          label: "Testing",
          items: [
            "frontend/testing/index",
            "frontend/testing/component-testing/index",
            "frontend/testing/e2e-testing/index",
            "frontend/testing/accessibility-testing/index",
          ],
        },
        // For larger sections, you could use autogenerated structure
        {
          type: "category",
          label: "Styling",
          items: [
            "frontend/styling/index",
            {
              type: "category",
              label: "Best Practices",
              items: ["frontend/styling/best-practices/index"],
            },
            {
              type: "category",
              label: "Architecture",
              items: [
                {
                  type: "autogenerated",
                  dirName: "frontend/styling/architecture",
                },
              ],
            },
            {
              type: "category",
              label: "Frameworks",
              items: [
                "frontend/styling/frameworks/index",
                {
                  type: "category",
                  label: "Component-Based",
                  items: [
                    {
                      type: "autogenerated",
                      dirName: "frontend/styling/frameworks/component-based",
                    },
                  ],
                },
                {
                  type: "category",
                  label: "CSS-in-JS",
                  items: [
                    {
                      type: "autogenerated",
                      dirName: "frontend/styling/frameworks/css-in-js",
                    },
                  ],
                },
                {
                  type: "category",
                  label: "Utility-First",
                  items: [
                    {
                      type: "autogenerated",
                      dirName: "frontend/styling/frameworks/utility-first",
                    },
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Layout",
              items: ["frontend/styling/layout/index"],
            },
            {
              type: "category",
              label: "Preprocessors",
              items: ["frontend/styling/preprocessors/index"],
            },
            {
              type: "category",
              label: "Responsive Design",
              items: ["frontend/styling/responsive-design/index"],
            },
            // Other categories with autogenerated subcategories
          ],
        },
        {
          type: "category",
          label: "Angular",
          items: [
            "frontend/angular/index",
            "frontend/angular/injectors",
            "frontend/angular/dependency-injection",
            {
              type: "category",
              label: "Design Patterns",
              items: [
                {
                  type: "category",
                  label: "Creational Patterns",
                  items: [
                    {
                      type: "autogenerated",
                      dirName:
                        "frontend/angular/design-patterns/creational-patterns",
                    },
                  ],
                },
                {
                  type: "category",
                  label: "Structural Patterns",
                  items: [
                    {
                      type: "autogenerated",
                      dirName:
                        "frontend/angular/design-patterns/structural-patterns",
                    },
                  ],
                },
                {
                  type: "category",
                  label: "Behavioural Patterns",
                  items: [
                    {
                      type: "autogenerated",
                      dirName:
                        "frontend/angular/design-patterns/behavioural-patterns",
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  devopsSidebar: [
    {
      type: "category",
      label: "DevOps",
      items: [
        {
          type: "autogenerated",
          dirName: "devops/patterns",
        },
        {
          type: "autogenerated",
          dirName: "devops/tools",
        },
      ],
    },
  ],
  systemDesignSidebar: [
    {
      type: "category",
      label: "System Design",
      items: [
        "system-design/index",
        {
          type: "category",
          label: "Software",
          items: [
            "system-design/software/index",
            "system-design/software/informatica-power-center",
            "system-design/software/kafka/kafka",
            "system-design/software/rabbitmq/rabbitmq",
          ],
        },
        {
          type: "category",
          label: "Concepts",
          items: [
            "system-design/concepts/index",
            "system-design/concepts/cloud",
          ],
        },
        {
          type: "category",
          label: "Architecture",
          items: [
            "system-design/architecture/index",
            {
              type: "category",
              label: "The Clean Architecture",
              items: ["system-design/architecture/clean-architecture/index"],
            },
          ],
        },
        {
          type: "category",
          label: "Projects examples of System Design",
          items: [
            "system-design/projects/index",
            "system-design/projects/private-cloud-platform/index",
          ],
        },
      ],
    },
  ],
  programmingLanguages: [
    {
      type: "category",
      label: "Programming Languages",
      items: ["languages/javascript/index", "languages/typescript/index"],
    },
  ],
};

export default sidebars;
